### Create an user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email" : "teyi@gmail.com",
    "password" : "teyi"
}


### Sign in as an existing user

POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email" : "sibi@gmail.com",
    "password" : "sibi"
}


### Get the currently sign user

GET  http://localhost:3000/auth/currentuser


### Signout
POST  http://localhost:3000/auth/signout


### Find a particular user with a given id

GET http://localhost:3000/auth/2


### Find all users with a giver email

GET  http://localhost:3000/auth?email=to@gmail.com


### Delete user with a given id

DELETE   http://localhost:3000/auth/3

### Update a user

PATCH    http://localhost:3000/auth/8
content-type: application/json

{
    "email" : "to@gmail.com"
}










